[2024-09-19 16:50:08,007] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_save_weather_data.fetch_weather_data manual__2024-09-19T16:49:38.497762+00:00 [queued]>
[2024-09-19 16:50:08,009] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_save_weather_data.fetch_weather_data manual__2024-09-19T16:49:38.497762+00:00 [queued]>
[2024-09-19 16:50:08,009] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-19 16:50:08,009] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-19 16:50:08,009] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-19 16:50:08,013] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-09-19 16:49:38.497762+00:00
[2024-09-19 16:50:08,015] {standard_task_runner.py:52} INFO - Started process 60794 to run task
[2024-09-19 16:50:08,018] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_save_weather_data', 'fetch_weather_data', 'manual__2024-09-19T16:49:38.497762+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/part2.py', '--cfg-path', '/var/folders/ks/w6y0t6b552bdg88w8kq5g_xc0000gn/T/tmpnf0y4ay_', '--error-file', '/var/folders/ks/w6y0t6b552bdg88w8kq5g_xc0000gn/T/tmp6b5leiui']
[2024-09-19 16:50:08,019] {standard_task_runner.py:80} INFO - Job 13: Subtask fetch_weather_data
[2024-09-19 16:50:13,033] {task_command.py:371} INFO - Running <TaskInstance: fetch_save_weather_data.fetch_weather_data manual__2024-09-19T16:49:38.497762+00:00 [running]> on host MBPdeCharmaine
[2024-09-19 16:50:18,084] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_save_weather_data
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-19T16:49:38.497762+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-19T16:49:38.497762+00:00
[2024-09-19 16:50:19,145] {part2.py:25} INFO - loading temperature ....
[2024-09-19 16:50:19,149] {python.py:173} INFO - Done. Returned value was: None
[2024-09-19 16:50:19,152] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=fetch_save_weather_data, task_id=fetch_weather_data, execution_date=20240919T164938, start_date=20240919T165008, end_date=20240919T165019
[2024-09-19 16:50:19,195] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-19 16:50:19,202] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
